# Generated by Django 4.0.7 on 2022-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hr_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(default='', max_length=50)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('company_city', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seeker_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('current_company_name', models.CharField(default='', max_length=50)),
                ('profession', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
