# Generated by Django 4.0.7 on 2022-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_profile',
            name='post',
            field=models.CharField(default='', max_length=50),
        ),
    ]
