# Generated by Django 4.0.7 on 2022-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_job', '0002_hr_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_profile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seeker_profile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
