# Generated by Django 4.0.7 on 2022-09-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_job', '0004_remove_hr_profile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_profile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seeker_profile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
