# Generated by Django 4.0.7 on 2022-09-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_job', '0005_hr_profile_username_seeker_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr_profile',
            old_name='company_email',
            new_name='email',
        ),
    ]
