# Generated by Django 4.0.7 on 2022-09-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_job', '0002_rename_company_email_hr_profile_email_and_more'),
        ('find_my_job', '0006_rename_company_email_hr_profile_email'),
    ]

    operations = [
    ]
